### ISSUE TITLE
Remove CSV file

### ISSUE THREAD

**Issue by morosebose** [morosebose/countries_data#6]
~Do we need the functionality of writing the database table out to a CSV file? We are not using it for anything right now and it might be good to remove that function if it's just taking up bits.~ **Fixed** in pull request #17

**Comment by jcmkang** [comment]
Hey Surajit! totally agree. We aren't using the csv file for anything front end related. As the database table as all the data that we need to query. 
It seems as if we need to just remove the writeCSV function @ line 195 and the function call @ line 213. 

Let me know if you agree and I want to try to do a pull request and fix the issue through the pull request,

**Comment by morosebose** [comment]
Agreed! Go ahead and do the pull req!

**Comment by morosebose** [comment]
Fixed in pull request #17
